# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('activationDate', models.DateField(auto_now_add=True)),
                ('postalCode', models.CharField(default=b'', max_length=6)),
                ('state', models.CharField(default=b'', max_length=2)),
                ('county', models.CharField(default=b'', max_length=32)),
                ('city', models.CharField(default=b'', max_length=32)),
                ('latitude', models.CharField(default=b'none', max_length=16)),
                ('longitude', models.CharField(default=b'none', max_length=16)),
                ('timeZone', models.CharField(default=b'none', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('activationDate', models.DateField(auto_now_add=True)),
                ('originalCapacity', models.IntegerField(blank=True, null=True)),
                ('currentCapacity', models.IntegerField(blank=True, null=True)),
                ('stateOfCharge', models.FloatField(blank=True, null=True)),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant')),
            ],
        ),
    ]
