# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=250)),
                ('role', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('companyName', models.CharField(blank=True, max_length=50, null=True)),
                ('companyAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('companyCityState', models.CharField(blank=True, max_length=50, null=True)),
                ('companyPostalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=250)),
                ('versionCreationTime', models.DateTimeField(auto_now_add=True)),
                ('recordStatus', models.IntegerField(default=1)),
                ('versionID', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants', models.IntegerField(blank=True, null=True)),
                ('firstday', models.DateField(blank=True, null=True)),
                ('lastday', models.DateField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantuuid', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('activationdate', models.DateField()),
                ('postalcode', models.CharField(default=b'', max_length=6)),
                ('state', models.CharField(default=b'', max_length=2)),
                ('county', models.CharField(default=b'', max_length=32)),
                ('city', models.CharField(default=b'', max_length=32)),
                ('latitude', models.CharField(default=b'none', max_length=16)),
                ('longitude', models.CharField(default=b'none', max_length=16)),
                ('timezone', models.CharField(default=b'none', max_length=64)),
                ('weathersource', models.CharField(blank=True, max_length=32, null=True)),
                ('dcrating', models.FloatField(blank=True, null=True)),
                ('derate', models.FloatField(blank=True, null=True)),
                ('trackertype', models.CharField(max_length=32)),
                ('tilt', models.IntegerField()),
                ('azimuth', models.IntegerField()),
                ('storageoriginalcapacity', models.FloatField(blank=True, null=True)),
                ('storagecurrentcapacity', models.FloatField(blank=True, null=True)),
                ('storagestateofcharge', models.FloatField(blank=True, null=True)),
                ('accountid', models.CharField(max_length=250)),
                ('recordstatus', models.IntegerField(default=1)),
                ('versioncreationtime', models.DateTimeField(auto_now_add=True)),
                ('versionid', models.IntegerField(default=1)),
                ('solaranywheresite', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sampleinterval', models.IntegerField()),
                ('WH_DIFF', models.FloatField()),
                ('GHI_DIFF', models.FloatField()),
                ('TMPAMB_AVG', models.FloatField(blank=True, null=True)),
                ('HPOA_DIFF', models.FloatField(blank=True, null=True)),
                ('recordstatus', models.IntegerField(default=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestTime', models.DateTimeField(auto_now_add=True)),
                ('responseTime', models.DateTimeField(blank=True, null=True)),
                ('plantUUID', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(max_length=16)),
                ('errorDetail', models.CharField(blank=True, max_length=1024, null=True)),
                ('s3Key', models.CharField(max_length=254)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.Account')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant')),
            ],
        ),
    ]
