# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
