# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvarray',
            old_name='plant',
            new_name='fkPlant',
        ),
        migrations.AlterField(
            model_name='plant',
            name='versionCreationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
