# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportrun',
            old_name='runscompletetime',
            new_name='runcompletetime',
        ),
    ]
