# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('arrayId', models.IntegerField()),
                ('trackerType', models.CharField(max_length=32)),
                ('tilt', models.IntegerField()),
                ('azimuth', models.IntegerField()),
                ('orientation', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
