# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportrun',
            old_name='observationendtime',
            new_name='observationstartdate',
        ),
        migrations.RemoveField(
            model_name='reportrun',
            name='observationstarttime',
        ),
        migrations.AddField(
            model_name='reportrun',
            name='observationenddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportrun',
            name='runscompletetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
