# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='observationstartdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
