# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0002_auto_20161028_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='reportrun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='osparc.ReportRun'),
        ),
    ]
