# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0002_auto_20161017_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planttimeseries',
            old_name='recordStatus',
            new_name='recordstatus',
        ),
        migrations.RenameField(
            model_name='planttimeseries',
            old_name='sampleInterval',
            new_name='sampleinterval',
        ),
        migrations.RenameField(
            model_name='planttimeseries',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
