# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0002_kpi_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcrating', models.FloatField(blank=True, null=True)),
                ('storageoriginalcapacity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'osparc_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(default=b'', max_length=2)),
                ('county', models.CharField(default=b'', max_length=32)),
                ('city', models.CharField(default=b'', max_length=32)),
                ('latitude', models.CharField(default=b'none', max_length=16)),
                ('longitude', models.CharField(default=b'none', max_length=16)),
                ('timezone', models.CharField(default=b'none', max_length=64)),
                ('weathersource', models.CharField(blank=True, max_length=32, null=True)),
                ('dcrating', models.FloatField(blank=True, null=True)),
                ('derate', models.FloatField(blank=True, null=True)),
                ('trackertype', models.CharField(max_length=32)),
                ('tilt', models.IntegerField()),
                ('azimuth', models.IntegerField()),
                ('storageoriginalcapacity', models.FloatField(blank=True, null=True)),
                ('storagecurrentcapacity', models.FloatField(blank=True, null=True)),
                ('storagestateofcharge', models.FloatField(blank=True, null=True)),
                ('accountid', models.CharField(max_length=250)),
                ('recordstatus', models.IntegerField(default=1)),
                ('versioncreationtime', models.DateTimeField(auto_now_add=True)),
                ('versionid', models.IntegerField(default=1)),
                ('solaranywheresite', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='description',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plantuuid',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='accountid',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='azimuth',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='county',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='dcrating',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='derate',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='recordstatus',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='solaranywheresite',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='state',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='storagecurrentcapacity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='storageoriginalcapacity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='storagestateofcharge',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='tilt',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='trackertype',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='versioncreationtime',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='versionid',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='weathersource',
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant'),
        ),
    ]
