# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0002_auto_20160925_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvarray',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant'),
        ),
    ]
