# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0002_auto_20160929_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('sampleInterval', models.IntegerField()),
                ('WH_DIFF', models.FloatField()),
                ('GHI_DIFF', models.FloatField()),
                ('TMPAMB_AVG', models.FloatField()),
                ('recordStatus', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PVArrayTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('sampleInterval', models.IntegerField()),
                ('HPOA_DIFF', models.FloatField()),
                ('recordStatus', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='fkAccount',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='pvarray',
            old_name='fkPlant',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='uploadactivity',
            old_name='fkAccount',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='uploadactivity',
            old_name='fkPlant',
            new_name='plant',
        ),
        migrations.AddField(
            model_name='pvarraytimeseries',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant'),
        ),
        migrations.AddField(
            model_name='pvarraytimeseries',
            name='pvArray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.PVArray'),
        ),
        migrations.AddField(
            model_name='planttimeseries',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant'),
        ),
    ]
