# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0002_auto_20161026_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='runsubmittime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
