# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0002_auto_20161006_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='storageCurrentCapacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='storageOriginalCapacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
