# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0003_auto_20161010_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttimeseries',
            name='TMPAMB_AVG',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
