# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0003_auto_20161026_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrun',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
