# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0004_auto_20161011_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttimeseries',
            name='HPOA_DIFF',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
