# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0004_reportrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
