# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0005_auto_20161026_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='plantfilter',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
