# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0005_auto_20161021_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetails',
            name='state',
        ),
        migrations.AddField(
            model_name='plant',
            name='state',
            field=models.CharField(default=b'', max_length=2),
        ),
    ]
