# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0006_auto_20161021_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordstatus', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField()),
                ('sampleinterval', models.IntegerField(blank=True, null=True)),
                ('firstinterval', models.DateTimeField()),
                ('lastinterval', models.DateTimeField()),
                ('yfavg', models.FloatField(blank=True, null=True)),
                ('yravg', models.FloatField(blank=True, null=True)),
                ('pravg', models.FloatField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportname', models.CharField(blank=True, max_length=254, null=True)),
                ('observationstarttime', models.DateTimeField(blank=True, null=True)),
                ('observationendtime', models.DateTimeField(blank=True, null=True)),
                ('plantpostalcode', models.CharField(blank=True, max_length=6, null=True)),
                ('plantstate', models.CharField(blank=True, max_length=2, null=True)),
                ('plantminsize', models.IntegerField(blank=True, null=True)),
                ('plantmaxsize', models.IntegerField(blank=True, null=True)),
                ('plantearliestactivationdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('plants', models.IntegerField(blank=True, null=True)),
                ('firstday', models.DateField(blank=True, null=True)),
                ('lastday', models.DateField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runsubmittime', models.DateTimeField(blank=True, null=True)),
                ('runstarttime', models.DateTimeField(blank=True, null=True)),
                ('runscompletetime', models.DateTimeField(blank=True, null=True)),
                ('observationstarttime', models.DateTimeField(blank=True, null=True)),
                ('observationendtime', models.DateTimeField(blank=True, null=True)),
                ('numberofobservations', models.IntegerField(blank=True, null=True)),
                ('numberofplants', models.IntegerField(blank=True, null=True)),
                ('totaldccapacity', models.FloatField(blank=True, null=True)),
                ('totalstoragecapacity', models.FloatField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osparc.ReportDefinition')),
            ],
        ),
    ]
