# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0007_plantreport_reportdefinition_reportkpi_reportrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdefinition',
            name='observationendtime',
        ),
        migrations.RemoveField(
            model_name='reportdefinition',
            name='observationstarttime',
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='observationenddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='observationstartdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
