# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0008_auto_20161024_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdefinition',
            old_name='plantearliestactivationdate',
            new_name='plantlatestactivationdate',
        ),
    ]
