# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osparc', '0009_auto_20161024_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdefinition',
            old_name='reportname',
            new_name='name',
        ),
    ]
